In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("supermarket_data.csv")

In [3]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [5]:
df.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [6]:
df = df.dropna()

np.int64(0)

In [8]:
df['Gender'] = df['Gender'].str.strip().str.lower()
df['Gender'] = df['Gender'].replace({'m': 'male', 'f': 'female'})

In [8]:
df['Gender'] = df['Gender'].str.strip().str.lower()
df['Gender'] = df['Gender'].replace({'m': 'male', 'f': 'female'})

In [9]:
df['Date'].head()

0     1/5/2019
1     3/8/2019
2     3/3/2019
3    1/27/2019
4     2/8/2019
Name: Date, dtype: object

In [12]:
df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y')

In [13]:
df['Date'] = df['Date'].dt.strftime('%d-%m-%Y')

In [14]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,female,Health and beauty,74.69,7,26.1415,548.9715,05-01-2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,female,Electronic accessories,15.28,5,3.8200,80.2200,08-03-2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,female,Home and lifestyle,46.33,7,16.2155,340.5255,03-03-2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,female,Health and beauty,58.22,8,23.2880,489.0480,27-01-2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,female,Sports and travel,86.31,7,30.2085,634.3785,08-02-2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [15]:
df.columns = df.columns.str.strip()        # Remove spaces
df.columns = df.columns.str.lower()        # Lowercase
df.columns = df.columns.str.replace(' ', '_')  # Replace spaces with underscore

In [16]:
df.head()

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5%,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,750-67-8428,Alex,Yangon,Member,female,Health and beauty,74.69,7,26.1415,548.9715,05-01-2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,female,Electronic accessories,15.28,5,3.8200,80.2200,08-03-2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,female,Home and lifestyle,46.33,7,16.2155,340.5255,03-03-2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,female,Health and beauty,58.22,8,23.2880,489.0480,27-01-2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,female,Sports and travel,86.31,7,30.2085,634.3785,08-02-2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [17]:
df.dtypes

invoice_id                  object
branch                      object
city                        object
customer_type               object
gender                      object
product_line                object
unit_price                 float64
quantity                     int64
tax_5%                     float64
sales                      float64
date                        object
time                        object
payment                     object
cogs                       float64
gross_margin_percentage    float64
gross_income               float64
rating                     float64
dtype: object

In [19]:
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

In [34]:
df['quantity'] = df['quantity'].astype(int)
df['unit_price'] = df['unit_price'].astype(float)
df['time'] = pd.to_datetime(df['time'])

C:\Users\gokul\AppData\Local\Temp\ipykernel_9960\3561629462.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['time'] = pd.to_datetime(df['time'])

In [35]:
df.dtypes

invoice_id                         object
branch                             object
city                               object
customer_type                      object
gender                             object
product_line                       object
unit_price                        float64
quantity                            int64
tax_5%                            float64
sales                             float64
date                       datetime64[ns]
time                       datetime64[ns]
payment                            object
cogs                              float64
gross_margin_percentage           float64
gross_income                      float64
rating                            float64
dtype: object

In [22]:
df['gender'] = df['gender'].str.strip()   # remove extra spaces
df['gender'] = df['gender'].str.lower()   # convert to lowercase

In [32]:
df['branch'] = df['branch'].str.strip().str.lower()
df['city'] = df['city'].str.strip().str.lower()
df['product_line'] = df['product_line'].str.strip().str.lower()
df['customer_type'] = df['customer_type'].str.strip().str.lower()
df['payment'] = df['payment'].str.strip().str.lower()

In [33]:
df.head()

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5%,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,750-67-8428,alex,yangon,member,female,health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,giza,naypyitaw,normal,female,electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,alex,yangon,normal,female,home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,alex,yangon,member,female,health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,alex,yangon,member,female,sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,ewallet,604.17,4.761905,30.2085,5.3

In [36]:
df.to_csv("cleaned_supermarket_data.csv", index=False)

In [37]:
import os
os.getcwd()

'C:\\Users\\gokul\\Downloads'